### ISSUE TITLE
Feature suggestion: in navigation mode, change q and e behavior to be perpendicular to view direction

### ISSUE THREAD

**Issue by NathanC** [SpectralVectors/RightMouseNavigation#15]
In Unity, when you're facing downwards, q moves you backwards in space and e moves you forwards. So the direction of "up" and "down" are relative to where you're facing. I find this behavior much more intuitive.

You can mimic this in blender with the combined keyboard movement of q + s (relative down, e.g., backwards if facing down), and w + e (relative up). It would be nice if that was the default behavior for q and e, as the combo keys, espeically q + s, are hard to hit and clunky.

idk if this is possible with the blender plugin API, but it would be a cool feature to have for this plugin.

**Comment by SpectralVectors** [comment]
I'm not sure about how to implement this one, my addon is essentially just a wrapper for Blender's Walk Navigation, so to do what you're suggesting you might have to edit the actual Walk Navigation code in Blender, and I'm not sure if that's exposed to Python or hard coded in C.

You could try registering a custom operator that calls both (down, backwards) at the same time, then edit the Walk Navigation to call your custom operator instead of whichever key you want to replace, but that's the best I can come up with off the top of my head.

This _may_ be a feature that would require a custom build of Blender.

**Comment by NathanC** [comment]
Yeah, I was figuring it wasn't possible with plugins, though I did consider the auto-key-combo-- the key combo changes the direction in other ways besides relative vertical though, so not ideal.

I'll leave this here for reference, but feel free to close if you'd like!

**Comment by SpectralVectors** [comment]
Hi NathanC, I'm going to close this issue, as it's a little older, and it's not on my list of planned features as yet.
It's a very good point, and one that I can't unsee now that you've pointed it out!
I won't rule it out from being implemented, but I'm not sure how I would do it.
Feel free to create a pull request if you're able to figure it out!
Thanks!
